### ISSUE TITLE
Starting a process with a command, and then interacting with it with subcommands?

### ISSUE THREAD

**Issue by zelanter** [fleipold/jproc#13]
Hi,

I was wondering if this library allows to start a process with a command, it stays active, and then you keep interacting with it over time with multiple commands and each time you get the output?

I see **.withInputStream** option in documentation, will it just use the inputstream as it is at creation time, or I can keep adding to inputstream to keep interacting with the process?

Thank you

**Comment by fleipold** [comment]
The focus on jproc is to pipe data into non-interactive external processes. A lot of its features like the error handling, automatic feeding of input and  consumption of output as well as the timeout solve issues that arise when calling non-interactive programs.

When interacting with a program a control thread would have have to read the output and supply input accordingly. This could be done using Java's process API directly. 

To your actual question: An input stream that you can add data to is a pipe. You could pass the piped input stream to the `.withInputStream` method and write data into the output stream end of the pipe. However this would create quite a bit of overhead over using the process API directly.
