### ISSUE TITLE
cd command is not working

### ISSUE THREAD

**Issue by Rupangkan** [fleipold/jproc#18]
cannot jump to other directories or drives

**Comment by fleipold** [comment]
@Rupangkan what are you trying to achieve. Cd is normally a built-in command of the shell, not an executable.

To set the working directory of a process you are invoking, please use the `withWorkingDirectory(dir)` method, see [example](https://github.com/fleipold/jproc#the-environment).

**Comment by Rupangkan** [comment]
> @Rupangkan what are you trying to achieve? `cd` is normally a built-in command of the shell, not an executable.
> 
> To set the working directory of a process you are invoking, please use the `withWorkingDirectory(dir)` method, see [example](https://github.com/fleipold/jproc#the-environment).

@fleipold Thank you, `withWorkingDirectory(dir)` is what i needed and is working just fine.
