### ISSUE TITLE
License: MIT or BSD?

### ISSUE THREAD

**Issue by kokorin** [fleipold/jproc#26]
Hello, 

In pom.xml it is stated that this project is distributed under MIT license:
```xml
    <licenses>
        <license>
            <name>MIT License</name>
            <url>http://www.opensource.org/licenses/mit-license.php</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
```

While project itself contains BSD license in LICENSE file.

Please clarify.

**Comment by fleipold** [comment]
BSD-3-Clause is it. I have fixed the license entry in the pom.
