### ISSUE TITLE
How do I import this project?

### ISSUE THREAD

**Issue by kubast2** [fleipold/jproc#27]
implementation 'org.buildobjects.jproc:2.6.2'

import org.buildobjects.jproc;
wrong

https://github.com/fleipold/jproc/blob/master/src/main/java/org/buildobjects/process/ByteArrayConsumptionThread.java#L1
import org.buildobjects.process;
wrong

I just don't understand java, why are things so needlessly complicated.

**Comment by fleipold** [comment]
@kubast2 as you mention a basic understanding of Java really helps with using this library. Essentially there are two steps:

1. The library needs to be on the class path. The way to do this depends on your build tool. You are giving the gradle line:
 
   ```groovy 
   implementation group: 'org.buildobjects', name: 'jproc', version: '2.6.2'
   ```

2. You'll need to import the classes you want to use into the namespace (or use fully qualified names):

   ```java
    import org.buildobjects.process.ProcBuilder;
 
    public class Main {

        public static void main(String[] args) {
            String output = ProcBuilder.run("echo", "Hello World!");
            System.out.println(output);
        }
    }
   ```

While Java has its fair share complexities, this is actually straight-forward in that it is similar to what you have to do in Python, Ruby or modern Java.
