### ISSUE TITLE
Migrate Build from Travis-ci.org to .com

### ISSUE THREAD

**Issue by systemhalted** [fleipold/jproc#34]
**Describe the bug**
The build is currently running on .org, which has stopped doing builds and is asking to migrate to .com version of the site.

Automatic builds are thus stalled. 

**To Reproduce**

A description/ code snippet
N/A

**Expected behavior**
The build should happen

**Actual Behaviour**

* What happened actually?
* How was it different from what you expected to happen?

Explained above 

**Context**

* Is there an exception/ output? Please paste the relevant bits into the ticket.
* What operating system did you use?
N/A

**Comment by fleipold** [comment]
@systemhalted , well spotted :). It looks like the travis folks have ended their free tier. We'll have to investigate alternatives (circle-ci comes to mind).

**Comment by systemhalted** [comment]
There is a free plan on Travis-ci.com as well.
