### ISSUE TITLE
Is there a way to use jproc to set/reset password of linux user

### ISSUE THREAD

**Issue by RhettButlerX** [fleipold/jproc#38]
Hi. I use jproc to create a user and I want to set a password.
My code is like
`new ProBuilder("passwd").withInput("XXXXXXX").withInput("XXXXXXX").run()`
and I got this
` STDERR: New password: Retype new password: Password change aborted.
  STDERR: New password: Password change aborted.
  STDERR: New password: Password change aborted.
  STDERR: passwd: Have exhausted maximum number of retries for service`
So, Is there a way to do this with jproc ?
Thank you.

**Comment by fleipold** [comment]
@RhettButlerX jproc is not aimed at scripting interactive commands. To change passwords in batch mode (i.e. not interactively) on GNU systems you might want to look into using [`chpasswd`](https://linux.die.net/man/8/chpasswd)
