### ISSUE TITLE
Maven repository doesn't include the jar files in version 2.8.1

### ISSUE THREAD

**Issue by javierfreire** [fleipold/jproc#39]
**Describe the bug**

Maven repo contains sources en javadoc, but doesn't contain the jar file or the pom file.

**To Reproduce**

You can see the files in  https://repo1.maven.org/maven2/org/buildobjects/jproc/2.8.1/ 

**Expected behavior**

**Actual Behaviour**

* What happened actually?
* How was it different from what you expected to happen?

**Context**

* Is there an exception/ output? Please paste the relevant bits into the ticket.
* What operating system did you use?

**Comment by gemron** [comment]
the same problem.

**Comment by fleipold** [comment]
Thanks for reporting this. Something must have gone wrong with the upload. I'll release 2.8.2 today.

**Comment by fleipold** [comment]
It looks like the new jar is available:

https://repo1.maven.org/maven2/org/buildobjects/jproc/2.8.2/
