### ISSUE TITLE
Make stderr also available

### ISSUE THREAD

**Issue by ybatrakov** [fleipold/jproc#9]
It would be nice to have process' stderr available to client like stdout is:
- via ProcResult
- via ProcBuilder setter like ProcBuilder.withErrorStream

Currently we can capture stderr only via ExternalProcessFailureException.

**Comment by ybatrakov** [comment]
Made some changes for that. Generally it works, will submit a pull request once the functionality and tests are ready.

**Comment by EdwinKM** [comment]
Fiddling a while to get stderr messages for git. Seems not implemented. Is someone working on this?

**Comment by ybatrakov** [comment]
I've implemented it in my fork of jproc and created a pull request. No response from @fleipold at the moment.

**Comment by fleipold** [comment]
Fixed in release 2.2.2

**Comment by EdwinKM** [comment]
Wow! that is really fast. Thanks, seems to work fine :)
